// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPybixYv51UZs63OnOwY72CjIdPrZZNcg',
    appId: '1:758425628979:web:359308a95e430233b24e46',
    messagingSenderId: '758425628979',
    projectId: 'cinema-hall-783de',
    authDomain: 'cinema-hall-783de.firebaseapp.com',
    databaseURL: 'https://cinema-hall-783de-default-rtdb.firebaseio.com',
    storageBucket: 'cinema-hall-783de.appspot.com',
    measurementId: 'G-R28VX19LGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_w3Ee-aovK5rU3Ei7Pr4yp8U74ZSBATk',
    appId: '1:758425628979:android:88371744bf485417b24e46',
    messagingSenderId: '758425628979',
    projectId: 'cinema-hall-783de',
    databaseURL: 'https://cinema-hall-783de-default-rtdb.firebaseio.com',
    storageBucket: 'cinema-hall-783de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjE0gyJdwj4VbC7-Hx0-_bqENWjwApZqs',
    appId: '1:758425628979:ios:f5fca80f89dd95e5b24e46',
    messagingSenderId: '758425628979',
    projectId: 'cinema-hall-783de',
    databaseURL: 'https://cinema-hall-783de-default-rtdb.firebaseio.com',
    storageBucket: 'cinema-hall-783de.appspot.com',
    iosBundleId: 'com.ishuji.cinemahall.cinemahall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPybixYv51UZs63OnOwY72CjIdPrZZNcg',
    appId: '1:758425628979:web:02d5507b1d3b2d38b24e46',
    messagingSenderId: '758425628979',
    projectId: 'cinema-hall-783de',
    authDomain: 'cinema-hall-783de.firebaseapp.com',
    databaseURL: 'https://cinema-hall-783de-default-rtdb.firebaseio.com',
    storageBucket: 'cinema-hall-783de.appspot.com',
    measurementId: 'G-QDVQMYENHZ',
  );
}
